import mongoose from "mongoose";

export type InvestorPortfolioModel = mongoose.Document & {
    user: mongoose.Schema.Types.ObjectId,
    currentBidAmount: number,
    currentBidCount: number,
    currentApprovedInvestmentAmount: number,
    currentApprovedInvestmentCount: number,
    expectedInterest: number,
    expectedRepayment: number,
    onTimePaymentAmount: number,
    onTimePaymentCount: number,
    delayPayment30Amount: number,
    delayPayment30Count: number,
    delayPayment60Amount: number,
    delayPayment60Count: number,
    delayPayment61Amount: number,
    delayPayment61Count: number,
    previousInvestmentAmount: number,
    previousInvestmentCount: number,
    previousRepayedAmount: number,
    previousRepayedCount: number,
    previousDelayedAmount: number,
    previousDelayedCount: number,
    previousWrittenOffAmount: number,
    previousWrittenOffCount: number,
    walletAmount: number,
    walletInvested: number,
    walletAvailable: number,
    paymentReceived: number,
    paymentPrincipal: number,
    paymentInterest: number,
    paymentOther: number,
    currentMonthlyExpectedPrincipal: number,
    currentMonthlyExpectedInterest: number,
    currentYearlyTotalInterest: number,
    createdAt: Date,
    updatedAt: Date,
};

const InvestorPortfolioSchema = new mongoose.Schema({
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    currentBidAmount: Number,
    currentBidCount: Number,
    currentApprovedInvestmentAmount: Number,
    currentApprovedInvestmentCount: Number,
    expectedInterest: Number,
    expectedRepayment: Number,
    onTimePaymentAmount: Number,
    onTimePaymentCount: Number,
    delayPayment30Amount: Number,
    delayPayment30Count: Number,
    delayPayment60Amount: Number,
    delayPayment60Count: Number,
    delayPayment61Amount: Number,
    delayPayment61Count: Number,
    previousInvestmentAmount: Number,
    previousInvestmentCount: Number,
    previousRepayedAmount: Number,
    previousRepayedCount: Number,
    previousDelayedAmount: Number,
    previousDelayedCount: Number,
    previousWrittenOffAmount: Number,
    previousWrittenOffCount: Number,
    walletAmount: Number,
    walletInvested: Number,
    walletAvailable: Number,
    paymentReceived: Number,
    paymentPrincipal: Number,
    paymentInterest: Number,
    paymentOther: Number,
    currentMonthlyExpectedPrincipal: Number,
    currentMonthlyExpectedInterest: Number,
    currentYearlyTotalInterest: Number,
    createdAt: Date,
    updatedAt: Date,
}, { timestamps: true });

const InvestorPortfolio: mongoose.Model<InvestorPortfolioModel> = mongoose.model<InvestorPortfolioModel>("InvestorPortfolio", InvestorPortfolioSchema, "investor_portfolios");
export default InvestorPortfolio;
