import mongoose from "mongoose";

export type InvestorPortfolioModel = mongoose.Document & {
    user: string,
    currentBidAmount: string,
    currentBidCount: string,
    currentApprovedInvestmentAmount: string,
    currentApprovedInvestmentCount: string,
    expectedInterest: string,
    expectedRepayment: string,
    onTimePaymentAmount: string,
    onTimePaymentCount: string,
    delayPayment30Amount: string,
    delayPayment30Count: string,
    delayPayment60Amount: string,
    delayPayment60Count: string,
    delayPayment61Amount: string,
    delayPayment61Count: string,
    previousInvestmentAmount: string,
    previousInvestmentCount: string,
    previousRepayedAmount: string,
    previousRepayedCount: string,
    previousDelayedAmount: string,
    previousDelayedCount: string,
    previousWrittenOffAmount: string,
    previousWrittenOffCount: string,
    walletAmount: string,
    walletInvested: string,
    walletAvailable: string,
    paymentReceived: string,
    paymentPrincipal: string,
    paymentInterest: string,
    paymentOther: string,
    currentMonthlyExpectedPrincipal: string,
    currentMonthlyExpectedInterest: string,
    currentYearlyTotalInterest: string,
    createdAt: Date,
    updatedAt: Date,
};

const InvestorPortfolioSchema = new mongoose.Schema({
    user: String,
    currentBidAmount: String,
    currentBidCount: String,
    currentApprovedInvestmentAmount: String,
    currentApprovedInvestmentCount: String,
    expectedInterest: String,
    expectedRepayment: String,
    onTimePaymentAmount: String,
    onTimePaymentCount: String,
    delayPayment30Amount: String,
    delayPayment30Count: String,
    delayPayment60Amount: String,
    delayPayment60Count: String,
    delayPayment61Amount: String,
    delayPayment61Count: String,
    previousInvestmentAmount: String,
    previousInvestmentCount: String,
    previousRepayedAmount: String,
    previousRepayedCount: String,
    previousDelayedAmount: String,
    previousDelayedCount: String,
    previousWrittenOffAmount: String,
    previousWrittenOffCount: String,
    walletAmount: String,
    walletInvested: String,
    walletAvailable: String,
    paymentReceived: String,
    paymentPrincipal: String,
    paymentInterest: String,
    paymentOther: String,
    currentMonthlyExpectedPrincipal: String,
    currentMonthlyExpectedInterest: String,
    currentYearlyTotalInterest: String,
    createdAt: Date,
    updatedAt: Date,
}, { timestamps: true });

const InvestorPortfolio: mongoose.Model<InvestorPortfolioModel> = mongoose.model<InvestorPortfolioModel>("InvestorPortfolio", InvestorPortfolioSchema, "investor_portfolios");
export default InvestorPortfolio;
