import mongoose from "mongoose";

export type LoanModel = mongoose.Document & {
    code: string,
    borrower: string,
    loanType: string,
    amount: number,
    totalBidAmount: number,
    availableBidAmount: number,
    progressPercent: number,
    period: number,
    loanPurpose: string,
    loanPurposeOther: string,
    aprPercent: number,
    eirPercent: number,
    investorFee: number,
    processingFee: number,
    documentPrepared: boolean,
    contractSigned: boolean,
    hasFollowUp: boolean,
    status: string,
    isNotified: boolean,
    openForInvestments: boolean,
    debtor: string,
    submittedDate: Date,
    closingDate: Date,
    expectedRepaymentDate: Date,
    realRepaymentDate: Date,
    loanDocument: string,
    confirmBy: string,
    confirmDate: Date,
    createdAt: Date,
    updatedAt: Date,
};

const LoanSchema = new mongoose.Schema({
    code: String,
    borrower: String,
    loanType: String,
    amount: Number,
    totalBidAmount: Number,
    availableBidAmount: Number,
    progressPercent: Number,
    period: Number,
    loanPurpose: String,
    loanPurposeOther: String,
    aprPercent: Number,
    eirPercent: Number,
    investorFee: Number,
    processingFee: Number,
    documentPrepared: Boolean,
    contractSigned: Boolean,
    hasFollowUp: Boolean,
    status: String,
    isNotified: Boolean,
    openForInvestments: Boolean,
    debtor: String,
    submittedDate: Date,
    closingDate: Date,
    expectedRepaymentDate: Date,
    realRepaymentDate: Date,
    loanDocument: String,
    confirmBy: String,
    confirmDate: Date,
    createdAt: Date,
    updatedAt: Date,
}, { timestamps: true });

const Loan: mongoose.Model<LoanModel> = mongoose.model<LoanModel>("Loan", LoanSchema, "loans");
export default Loan;
